name: Deploy React App to Surge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./dist bitbucket-pipleines.surge.sh --token ${{ secrets.SURGE_TOKEN }}